name: dp261-g2

channels:
  - conda-forge

dependencies:
  - python=3.12
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - ipykernel
  - plotly
  - pip

  - pip:
      - dvc
      - streamlit
      - shap
      - xgboost
      - joblib
      - requests